def deep_lists():
    list1 = [
        "What is Chandler's job?",
        "Who played Rachel Green?",
        "What is Ross's job?",
        "Who did Monica marry?",
        "What's Joey's catchphrase?",
        "What's Phoebe's twin's name?",
        "What's Rachel's first job?",
        "Who was Ross's first wife?",
        "What's Monica's biggest fear?",
        "What's Joey's favorite food?",
        "What's Chandler's middle name?",
        "Who was Chandler's roommate?",
        "What's Phoebe's famous song?",
        "How many times did Ross marry?",
        "What's Monica's job?",
        "Who is Rachel's sister?",
        "What's Joey's favorite pasta?",
        "What's Chandler's sarcastic line?",
        "What does Ross study?",
        "What's Monica's apartment number?",
        "Who plays Chandler Bing?",
        "What's Rachel's hometown?",
        "What's Phoebe's profession?",
        "Who is Joey's agent?",
        "What's Ross's son's name?",
        "What's Monica's brother's name?",
        "What's Phoebe's favorite drink?",
        "What's Rachel's ex-fiancé's name?",
        "What's Chandler's father's job?",
        "What's Joey's imaginary friend?",
        "What's Ross's second wife's name?",
        "Who did Phoebe marry?",
        "What's Monica's wedding style?",
        "What's Rachel's favorite movie?",
        "What's Chandler's later job?",
        "What's Joey's full name?",
        "What's Ross's daughter's name?",
        "What's Phoebe's mother's name?",
        "What's Monica's competitive trait?",
        "What's Rachel's fashion job?",
        "What's Chandler's New Year's resolution?",
        "What does Joey never share?",
        "What's Ross's exact profession?",
        "What's Phoebe's half-brother's name?",
        "What's Monica and Ross's dad?",
        "What's Rachel's baby name?",
        "What's Joey's stuffed penguin?",
        "What's Chandler's proposal line?",
        "What's Monica's secret closet?",
        "What's Ross's leather pants moment?",
        "Who played Monica Geller?",
        "What's Phoebe's wedding location?",
        "What's Rachel's first kiss with Ross?",
        "What's Monica's nickname for Chandler?",
        "What's Joey's favorite sandwich?",
        "What's Ross's monkey's name?",
        "What's Phoebe's Smelly Cat job?",
        "What's Chandler's old roommate Kip?",
        "What's Rachel's green dress moment?",
        "What's Monica's Thanksgiving turkey?",
        "What's Joey's pickup line?",
        "What's Ross's breakup excuse?",
        "What's Phoebe's odd phrase?",
        "What's Monica's excited line?",
        "What's Chandler's stuttered phrase?",
        "What's Joey's food rule?",
        "What's Ross's moving line?",
        "What's Phoebe's secret knowledge line?",
        "What's Monica's special number?",
        "What's Rachel's pregnancy line?",
        "What's Joey's soap role?",
        "What's Chandler's ad job?",
        "What's Ross's museum job?",
        "What's Phoebe's massage job?",
        "What's Monica's chef role?",
        "What's Rachel's Bloomingdale's role?",
        "What's Joey's mafia film?",
        "What's Chandler's Tulsa assignment?",
        "What's Ross's tan mishap?",
        "What's Monica's jam plan?",
        "What's Phoebe's surrogacy?",
        "What's Rachel's pregnancy?",
        "What's Chandler's fertility issue?",
        "What's Joey's soap brain surgery?",
        "What's Ross's fake accent?",
        "What's Monica's thunder stealing?",
        "What's Phoebe's street name?",
        "What's Rachel's pregnancy craving?",
        "What's Chandler's bracelet?",
        "What's Joey's Porsche?",
        "What's Ross's teeth whitening?",
        "What's Monica's hair humidity?",
        "What's Phoebe's guitar chords?",
        "What's Rachel's trifle dessert?",
        "What's Chandler's bubble bath?",
        "What's Joey's identical twin?",
        "What's Ross's keyboard music?",
        "What's Monica's dirty girl?",
        "What's Phoebe's policeman boyfriend?",
        "What's Rachel's date with a movie star?",
        "What's Sheldon's catchphrase?",
        "What does Sheldon study?",
        "What's Howard's job?",
        "Who is Leonard's girlfriend?",
        "What's Penny's job?",
        "Who played Sheldon Cooper?",
        "What's Raj's dog's name?",
        "What's Amy's profession?",
        "What's Bernadette's job?",
        "What's Sheldon's spot?",
        "What's Leonard's profession?",
        "What's Howard's astronaut nickname?",
        "What's Penny's maiden name?",
        "What's Sheldon's roommate agreement?",
        "What's Raj's phobia?",
        "What's Howard's mother's voice?",
        "What's Sheldon's favorite takeout?",
        "What's Leonard's mom's job?",
        "What's Amy's catchphrase?",
        "What's Bernadette's voice like?",
        "What's Sheldon's Bazinga?",
        "Who did Sheldon marry?",
        "What's Raj's job?",
        "What's Howard's degree?",
        "What's Penny's acting role?",
        "What's Leonard's allergy?",
        "What's Sheldon's train love?",
        "What's Amy's harp?",
        "What's Bernadette's degree?",
        "What's Raj's siblings?",
        "What's Barney's catchphrase?",
        "What's Ted's profession?",
        "Who is Robin's ex?",
        "What's Marshall's favorite game?",
        "What's Lily's job?",
        "Who is the mother's name?",
        "What's Barney's job?",
        "What's Ted's college?",
        "What's Robin's catchphrase?",
        "What's Marshall's height?",
        "What's Lily's maiden name?",
        "Who played Ted Mosby?",
        "What's Barney's apartment?",
        "What's Robin's job?",
        "What's Ted's kids' names?",
        "What's Marshall's job?",
        "What's Lily's debt?",
        "What's Barney's playbook?",
        "What's Ted's yellow umbrella?",
        "What's Robin Sparkles?",
        "What's Marshall's car?",
        "What's Lily's teaching?",
        "What's Barney's real name?",
        "What's Ted's first date?",
        "What's Robin's dogs?",
        "What's Phil's job?",
        "Who is Claire's husband?",
        "What's Gloria's first language?",
        "What's Cam's job?",
        "What's Mitchell's job?",
        "Who is Manny's mother?",
        "What's Haley's baby name?",
        "What's Alex's school?",
        "What's Luke's hobby?",
        "What's Jay's company?",
        "What's Gloria's son's name?",
        "What's Phil's catchphrase?",
        "What's Claire's job?",
        "What's Cam's hometown?",
        "What's Mitchell's fear?",
        "What's Lily's full name?",
        "What's Phil's magic?",
        "What's Gloria's hot sauce?",
        "What's Jay's dog?",
        "What's Cam's clown name?",
        "What's Haley's husband?",
        "What's Alex's boyfriend?",
        "What's Luke's business?",
        "What's Manny's passion?",
        "What's Phil's real estate?",
        "What's Michael's catchphrase?",
        "What does Dwight sell?",
        "Who is Jim's wife?",
        "What's Pam's job?",
        "What's Michael's film?",
        "Who played Michael Scott?",
        "What's Dwight's beet farm?",
        "What's Jim's prank?",
        "What's Pam's art?",
        "What's Angela's cats?",
        "What's Kevin's band?",
        "What's Stanley's crossword?",
        "What's Creed's job?",
        "What's Ryan's title?",
        "What's Kelly's favorite?",
        "What's Toby's role?",
        "What's Dunder Mifflin?",
        "What's Michael's mug?",
        "What's Jim's alias?",
        "What's Dwight's cousin Mose?",
        "What's Pam's mom?",
        "What's Jan's job?",
        "What's Andy's college?",
        "What's Erin's name?",
        "What's Phyllis's husband?",
        "What's Jake's catchphrase?",
        "What's Amy's job?",
        "Who is Holt's husband?",
        "What's Rosa's weapon?",
        "What's Boyle's food blog?",
        "What's Terry's yogurt?",
        "What's Gina's dance team?",
        "What's Scully's partner?",
        "What's Hitchcock's chair?",
        "What's Jake's favorite movie?",
        "What's Amy's binder?",
        "What's Holt's dog?",
        "What's Rosa's voice?",
        "What's Boyle's son?",
        "What's Terry's nickname?",
        "What's Gina's catchphrase?",
        "What's Jake's dad?",
        "What's Amy's husband?",
        "What's Holt's tell?",
        "What's Rosa's bike?",
        "What's Jerry's job?",
        "What's George's job?",
        "What's Elaine's job?",
        "What's Kramer's first name?",
        "What's Jerry's apartment?",
        "What's George's catchphrase?",
        "What's Elaine's dance?",
        "What's Kramer's coffee?",
        "What's Seinfeld about?",
        "Who played George Costanza?",
        "What's Newman's job?",
        "What's Jerry's car?",
        "What's Elaine's boss?",
        "What's George's fiancée?",
        "What's Kramer's lawyer?",
        "What's Leslie's job?",
        "What's Ron's favorite food?",
        "What's April's husband?",
        "What's Andy's band?",
        "What's Tom's business?",
        "What's Donna's car?",
        "What's Ben's job?",
        "What's Chris's catchphrase?",
        "What's Jerry's real name?",
        "What's Leslie's waffles?",
        "What's Homer's catchphrase?",
        "What's Marge's hair?",
        "What's Bart's catchphrase?",
        "What's Lisa's instrument?",
        "What's Maggie's enemy?",
        "What's Homer's job?",
        "What's Springfield?",
        "Who voices Homer?",
        "What's Krusty's name?",
        "What's Mr. Burns' phrase?",
        "What's Charlie's job?",
        "What's Alan's profession?",
        "What's Jake's favorite phrase?",
        "Who played Charlie Harper?",
        "What's Berta's role?",
        "What's Abed's favorite show?",
        "What's Troy's catchphrase?",
        "What's Pierce's company?",
        "What's Jeff's job?",
        "What's Annie's school supply?",
        "What's Eric's car?",
        "What's Fez's country?",
        "What's Kelso's catchphrase?",
        "What's Donna's job?",
        "What's Hyde's sunglasses?",
        "What's Will's catchphrase?",
        "What's Carlton's dance?",
        "Who played Uncle Phil?",
        "What's Ashley's singing?",
        "What's Hilary's job?",
        "What's Eleanor's secret?",
        "What's Chidi's job?",
        "What's Tahani's name drop?",
        "What's Janet's role?",
        "What's Michael's true identity?",
        "What's Frasier's job?",
        "What's Niles's wife?",
        "What's Roseanne's family?",
        "What's Al Bundy's job?",
        "What's Dan Conner's business?",
        "What's Carrie's husband?",
        "What's Moesha's family?",
        "What's Fresh Off Boat restaurant?",
        "What's Black-ish family name?",
        "What's The Goldbergs era?",
        "What's Schitt's Creek motel?",
        "What's Ted Lasso's job?",
        "What's Alexis's catchphrase?",
        "What's Patsy's job?",
        "What's Derry Girls setting?"
    ]

    list2 = [
        "What should I cook today?",
        "How can I sleep better?",
        "How do I stay focused?",
        "What should I pack?",
        "How do I clean my shoes?",
        "What's an easy breakfast?",
        "How can I save money?",
        "What should I do today?",
        "How do I wake up early?",
        "What's a quick lunch?",
        "How do I organize my room?",
        "What can I do when bored?",
        "How can I study better?",
        "What's an easy dinner?",
        "How do I plan my day?",
        "How do I boil eggs?",
        "What's a healthy snack?",
        "How can I stop procrastinating?",
        "What should I cook for two?",
        "How do I remove stains?",
        "What's a good home workout?",
        "How do I make coffee at home?",
        "What should I read next?",
        "How do I make a budget?",
        "What's a good morning routine?",
        "How can I relax after work?",
        "What's a quick pasta recipe?",
        "How do I clean a microwave?",
        "What should I wear today?",
        "How can I improve my memory?",
        "What's an easy soup?",
        "How do I organize my desk?",
        "What's a cheap meal idea?",
        "How can I make new friends?",
        "What's a good evening routine?",
        "How do I plan my week?",
        "What's a fun hobby to start?",
        "How do I fix a leaky faucet?",
        "What should I plant in a small garden?",
        "How do I stop overthinking?",
        "What's a quick dessert?",
        "How do I clean windows?",
        "What should I pack for a beach day?",
        "How can I drink more water?",
        "What's a good podcast?",
        "How do I write a to-do list?",
        "What's a cheap travel destination?",
        "How can I reduce stress?",
        "What's a good lunch meal prep?",
        "How do I organize my closet?",
        "What's a good workout split?",
        "How do I make a smoothie?",
        "How can I wake up without snooze?",
        "What's a tasty chicken recipe?",
        "How do I clean a bathroom?",
        "What should I buy for a new home?",
        "What's a good side hustle?",
        "How can I improve my posture?",
        "What's a quick breakfast for kids?",
        "How do I plan a road trip?",
        "What's a good book to read?",
        "How can I focus on studying?",
        "What's a healthy dinner idea?",
        "How do I clean a laptop?",
        "What should I wear to an interview?",
        "How do I start running?",
        "What's a fun family game?",
        "How can I sleep through the night?",
        "What's a simple cake recipe?",
        "How do I organize papers?",
        "What's a good budgeting app?",
        "How do I stop snacking?",
        "What should I pack for camping?",
        "What's a good ab workout?",
        "How can I save on groceries?",
        "What's a quick stir fry?",
        "How do I clean a stove?",
        "What should I do on a rainy day?",
        "How can I be more productive?",
        "What's a nice outfit for work?",
        "How do I make iced tea?",
        "What's a good TV show to binge?",
        "How can I learn a new language?",
        "What's a fast breakfast?",
        "How do I organize my kitchen?",
        "What should I do on Sunday?",
        "How can I reduce screen time?",
        "What's a good warm-up?",
        "How do I clean a shower?",
        "What's a good gift idea?",
        "How can I stay motivated?",
        "What's a quick salad?",
        "How do I plan meals?",
        "What should I pack for a flight?",
        "How do I make a smoothie bowl?",
        "What's a fun hobby at home?",
        "How can I improve my handwriting?",
        "What's a healthy office lunch?",
        "How do I clean a keyboard?",
        "What should I do in a power outage?",
        "How can I save for a trip?",
        "What's a quick breakfast sandwich?",
        "How do I organize my emails?",
        "What's a good bodyweight workout?",
        "How do I clean a carpet?",
        "What should I plant in spring?",
        "How can I reduce anxiety?",
        "What's a simple pasta sauce?",
        "How do I write a resume?",
        "What's a good stretching routine?",
        "What should I do on a long flight?",
        "How can I be a morning person?",
        "What's a cheap hobby?",
        "How do I clean silver?",
        "What's a good party game?",
        "How can I stop biting nails?",
        "What's a quick oatmeal?",
        "How do I organize my phone?",
        "What should I pack for the gym?",
        "How can I make more time?",
        "What's a good yoga pose?",
        "How do I clean a blender?",
        "What should I watch tonight?",
        "What's a healthy smoothie?",
        "How do I unclog a drain?",
        "How can I improve my speaking?",
        "What's a quick rice dish?",
        "How do I plan a birthday?",
        "What's a good desk setup?",
        "What should I do after work?",
        "How can I eat less sugar?",
        "What's a simple bread recipe?",
        "How do I clean a fridge?",
        "What should I pack for a hike?",
        "How can I learn faster?",
        "What's a good cardio workout?",
        "How do I organize a garage?",
        "What's a nice thank-you gift?",
        "How can I calm down?",
        "What's a quick egg breakfast?",
        "How do I clean a faucet?",
        "What should I do this weekend?",
        "How can I reduce waste?",
        "What's a good book genre?",
        "How do I make a meal plan?",
        "What should I pack for a picnic?",
        "How can I improve flexibility?",
        "What's a simple soup recipe?",
        "How do I clean my phone?",
        "What's a good family movie?",
        "How can I wake up refreshed?",
        "What's a fast rice meal?",
        "How do I organize my time?",
        "What should I wear to a wedding?",
        "How do I start meditating?",
        "What's a good workout app?",
        "How do I clean a couch?",
        "What should I do on a day off?",
        "How can I boost my mood?",
        "What's a quick pancake recipe?",
        "How do I pack light?",
        "What's a good side dish?",
        "How can I improve my sleep schedule?",
        "What's a simple curry recipe?",
        "How do I clean a mirror?",
        "What should I pack for a cruise?",
        "How can I stay awake?",
        "What's a good chicken marinade?",
        "How do I organize my fridge?",
        "What's a fun solo activity?",
        "How can I stop worrying?",
        "What's a quick fish recipe?",
        "How do I clean a mattress?",
        "What should I plant in summer?",
        "How can I practice deep breathing?",
        "What's a good soup for colds?",
        "How do I make a salad dressing?",
        "What's a good family activity?",
        "How can I be more organized?",
        "What's a quick no-egg breakfast?",
        "How do I clean a bathtub?",
        "What should I do with old clothes?",
        "How can I make extra money?",
        "What's a good strength routine?",
        "How do I organize a pantry?",
        "What should I pack for a festival?",
        "How can I improve my focus?",
        "What's a simple guacamole?",
        "How do I clean a dishwasher?",
        "What's a good game night idea?",
        "How can I reduce back pain?",
        "What's a quick vegetarian dinner?",
        "How do I plan a trip?",
        "What should I do on a snow day?",
        "How can I improve my diet?",
        "What's a good beginner workout?",
        "How do I clean a ceiling fan?",
        "What should I pack for a long drive?",
        "How can I stop feeling tired?",
        "What's a quick tuna recipe?",
        "How do I organize my books?",
        "What's a good creative hobby?",
        "How can I manage stress?",
        "What's a simple chili recipe?",
        "How do I clean a sink?",
        "What should I do with ripe bananas?",
        "How can I make mornings easier?",
        "What's a good lower body workout?",
        "How do I organize my makeup?",
        "What should I pack for a work trip?",
        "How can I improve my vocabulary?",
        "What's a quick beef recipe?",
        "How do I stop drain smells?",
        "What's a good audiobook?",
        "How can I be more positive?",
        "What's a simple tomato soup?",
        "How do I organize my tools?",
        "What should I wear for running?",
        "How can I stop drinking soda?",
        "What's a good upper body workout?",
        "How do I clean a grill?",
        "What's a fun cheap date idea?",
        "How can I improve my English?",
        "What's a quick shrimp recipe?",
        "How do I make a grocery list?",
        "What should I do during lunch break?",
        "How can I reduce clutter?",
        "What's a good core workout?",
        "How do I clean a coffee maker?",
        "What should I pack for swimming?",
        "How can I improve my credit?",
        "What's a simple salsa recipe?",
        "How do I organize my shoes?",
        "What's a good board game?",
        "How can I stop feeling overwhelmed?",
        "What's a quick potato recipe?",
        "How do I clean a leather sofa?",
        "What should I do before bed?",
        "How can I learn to code?",
        "What's a good hamstring stretch?",
        "How do I organize my bills?",
        "What should I wear on a date?",
        "How can I boost energy?",
        "What's a simple hummus recipe?",
        "How do I clean a toaster?",
        "What's a good outdoor hobby?",
        "How can I be more confident?",
        "What's a quick lentil recipe?",
        "How do I plan a party?",
        "What should I do with spare time?",
        "How can I improve my typing?",
        "What's a good balance exercise?",
        "How do I clean a rug?",
        "What should I pack for a baby?",
        "How can I make new habits?",
        "What's a simple omelette?",
        "How do I organize my recipes?",
        "What's a fun indoor activity?",
        "How can I reduce eye strain?",
        "What's a quick couscous recipe?",
        "How do I clean a fan?",
        "What should I do on a staycation?",
        "How can I improve my listening?",
        "What's a good cardio dance?",
        "How do I organize my notes?",
        "What should I pack for winter travel?",
        "How can I stop comparing myself?",
        "What's a simple pesto recipe?",
        "How do I clean tile floors?",
        "What's a fun group activity?",
        "How can I manage my time?",
        "What's a good interval workout?",
        "How do I organize a small space?",
        "What should I do with old books?",
        "How can I improve my skin?",
        "What's a quick bean recipe?",
        "How do I clean a laptop screen?",
        "What's a good road trip snack?",
        "How can I stay hydrated?",
        "What's a simple vinaigrette?",
        "How do I organize my calendar?",
        "What should I wear to stay warm?",
        "How can I reduce food waste?",
        "What's a good beginner yoga routine?",
        "How do I clean a shower curtain?",
        "What should I pack for a cabin?",
        "How can I improve my balance?",
        "What's a simple breakfast casserole?",
        "How do I organize my photos?",
        "What's a fun summer activity?",
        "How can I stop overspending?",
        "What's a good full-body workout?",
        "How do I clean a shower head?",
        "What should I do before a trip?",
        "How can I improve my stamina?",
        "What's a simple egg salad?",
        "How do I organize my receipts?",
        "What's a good learning podcast?",
        "How can I relax before bed?",
        "What's a quick avocado toast?"
    ]

    list3 = [
        "Why is the sky blue?",
        "How does gravity work?",
        "What's the largest ocean?",
        "How old is the Earth?",
        "Why do cats purr?",
        "Who invented the telephone?",
        "How far is the Moon?",
        "What is DNA?",
        "How many bones do humans have?",
        "What's the smallest country?",
        "Why do stars shine?",
        "How do airplanes fly?",
        "What causes rainbows?",
        "How deep is the ocean?",
        "Why do we dream?",
        "How do magnets work?",
        "What is the speed of light?",
        "Why do leaves change color?",
        "How many planets are there?",
        "What is a black hole?",
        "Why do we yawn?",
        "Who invented the light bulb?",
        "What's the largest desert?",
        "How does immunity work?",
        "What causes thunder?",
        "Why is the sea salty?",
        "How do birds migrate?",
        "What is the longest river?",
        "Why do we have seasons?",
        "What is the human genome?",
        "How do bees make honey?",
        "What's the tallest mountain?",
        "Why do fireflies glow?",
        "What is photosynthesis?",
        "How many continents are there?",
        "Why do we hiccup?",
        "Who was the first president?",
        "How old is the universe?",
        "What's the capital of Japan?",
        "Why do dogs wag their tails?",
        "How do fish breathe?",
        "What is the periodic table?",
        "How do volcanoes erupt?",
        "What causes earthquakes?",
        "Why do we blush?",
        "How do telescopes work?",
        "What's the fastest animal?",
        "How does the Internet work?",
        "Why do onions make us cry?",
        "What is the Goldilocks zone?",
        "Who painted the Mona Lisa?",
        "How many languages are there?",
        "Why do we have fingerprints?",
        "What is the deepest lake?",
        "How do prisms split light?",
        "What is dark matter?",
        "Why do cats have whiskers?",
        "How do submarines work?",
        "What's the largest mammal?",
        "How old are dinosaurs?",
        "Why do we sneeze?",
        "Who invented the computer?",
        "What's the smallest planet?",
        "How do solar panels work?",
        "What causes tides?",
        "Why do we get goosebumps?",
        "What is the equator?",
        "How do enzymes work?",
        "What's the longest wall?",
        "Why do birds sing?",
        "What is a supernova?",
        "How do clouds form?",
        "Why is Mars red?",
        "What is the ozone layer?",
        "How do planes stay in the air?",
        "Who discovered penicillin?",
        "What's the hottest planet?",
        "How do coral reefs form?",
        "Why do we need sleep?",
        "What is antimatter?",
        "How do bats see?",
        "What's the largest country?",
        "Why do leaves fall?",
        "What is the Big Bang?",
        "How do glaciers move?",
        "Why do some flowers smell?",
        "What is the Great Barrier Reef?",
        "How does Wi-Fi work?",
        "What is the speed of sound?",
        "Who invented the airplane?",
        "What's the rarest blood type?",
        "How do snakes smell?",
        "Why do stars twinkle?",
        "What's the largest island?",
        "How does the brain work?",
        "What is a fossil?",
        "How do tornadoes form?",
        "What is the carbon cycle?",
        "Why do we get wrinkles?",
        "What is a galaxy?",
        "How does a compass work?",
        "What is electricity?",
        "Why do we age?",
        "Who invented the radio?",
        "What's the deepest trench?",
        "How do plants drink water?",
        "What causes wind?",
        "Why do dreams feel real?",
        "What is a nanobot?",
        "How do touchscreens work?",
        "What's the largest flower?",
        "How do animals hibernate?",
        "Why do we have eyebrows?",
        "What is the Earth's core?",
        "How does light bend?",
        "What causes snow?",
        "What is a tsunami?",
        "How do microwaves heat food?",
        "Who discovered gravity?",
        "What's the smallest bone?",
        "Why do some fish glow?",
        "How does herd immunity work?",
        "How do chameleons change color?",
        "What's the widest river?",
        "What is a meteor?",
        "How does herd immunity work?",
        "Why is blood red?",
        "What is a light-year?",
        "Who built the pyramids?",
        "How do satellites orbit?",
        "What's the largest bird?",
        "How do spiders make silk?",
        "What causes lightning?",
        "Why do we have different blood types?",
        "What is a continent?",
        "How do dolphins communicate?",
        "What is the water cycle?",
        "Why do mosquitoes bite?",
        "What is the Ring of Fire?",
        "How do brakes work?",
        "What's the oldest tree?",
        "How do penguins stay warm?",
        "Why do we have toenails?",
        "What is a nebula?",
        "How do wind turbines work?",
        "What causes ocean currents?",
        "Who invented the internet?",
        "What is the Milky Way?",
        "Why do we sweat?",
        "How do bats navigate?",
        "What's the largest volcano?",
        "What is an mRNA vaccine?",
        "Why is the sky dark at night?",
        "What is zero gravity?",
        "How do magnets attract?",
        "What causes the aurora?",
        "What is the solar system?",
        "How do plants make oxygen?",
        "Why do whales breach?",
        "What is a lunar eclipse?",
        "How do cells divide?",
        "Who invented the wheel?",
        "What is the coldest place?",
        "How do octopus camouflage?",
        "Why do we have wisdom teeth?",
        "What is the Kuiper Belt?",
        "How do jet engines work?",
        "What's the fastest fish?",
        "How do hurricanes form?",
        "What is a semiconductor?",
        "Why do leaves have veins?",
        "What is the Roman Empire?",
        "How do sound waves travel?",
        "Who was Cleopatra?",
        "What's the largest planet?",
        "How do turtles sleep?",
        "Who built the Great Wall?",
        "Why do we need vitamin D?",
        "How do electric cars work?",
        "What is the Panama Canal?",
        "What causes fog?",
        "How do bees communicate?",
        "Who invented paper?",
        "What is the Amazon?",
        "How does refraction work?",
        "Why do cats land on their feet?",
        "What is a chromosome?",
        "How do glaciers melt?",
        "What's the largest fish?",
        "How do deep sea fish see?",
        "What is a delta?",
        "Who was Albert Einstein?",
        "How do mirrors reflect?",
        "Why do we have two ears?",
        "What is the greenhouse effect?",
        "How do ants carry food?",
        "What's the fastest land animal?",
        "What causes hail?",
        "What is the human microbiome?",
        "How do crystals form?",
        "Who invented the steam engine?",
        "What is the tallest tree?",
        "Why do we have eyelashes?",
        "How do rockets fly?",
        "Where can you see auroras?",
        "What is an equinox?",
        "How do snakes shed skin?",
        "Who was Isaac Newton?",
        "What is a food chain?",
        "Why do dogs howl?",
        "How do submarines dive?",
        "What's the rarest element?",
        "How do birds fly?",
        "What causes low tide?",
        "What is a rain shadow?",
        "Who painted the Sistine Chapel?",
        "How do ears hear?",
        "What is the Great Lakes?",
        "Why do we forget dreams?",
        "How do geysers erupt?",
        "What is the deepest ocean trench?",
        "What causes static electricity?",
        "How do camels store water?",
        "Who invented the smartphone?",
        "What is the smallest bird?",
        "Why do lips chap?",
        "How do plants grow?",
        "What is the Earth's atmosphere?",
        "How do magnets repel?",
        "What is a supercontinent?",
        "What causes waves?",
        "Who wrote the Odyssey?",
        "Why do whales sing?",
        "What is a black box?",
        "How do planes land?",
        "What causes lunar phases?",
        "Who discovered radiation?",
        "What is the Great Sphinx?",
        "How do penguins swim?",
        "Why do we need iron?",
        "What is a black widow?",
        "How do drones fly?",
        "What is the Sahara?",
        "What causes avalanches?",
        "How do bees see?",
        "What is the speed of Earth's rotation?",
        "Why do tears taste salty?",
        "Who invented the printing press?",
        "What is the largest moon?",
        "How do mosquitoes find you?",
        "What is the biosphere?",
        "What is a double rainbow?",
        "How do whales sleep?",
        "What is the Space Station?",
        "Why do leaves have different shapes?",
        "What is the lithosphere?",
        "How do birds navigate?",
        "Who was Galileo?",
        "What is the biggest snake?",
        "How do fish swim?",
        "What causes a mirage?",
        "What is the human brain made of?",
        "Why do fire ants sting?",
        "What is the largest coral reef?",
        "How do parrots talk?",
        "What breaks the sound barrier?",
        "Who founded Rome?",
        "How do bacteria reproduce?",
        "What is the Great Pyramid?",
        "Why do we shiver?",
        "What is the troposphere?",
        "How do lasers work?",
        "What causes a solar eclipse?",
        "Why do some animals have spots?",
        "What is the smallest country in Africa?",
        "How do elephants communicate?",
        "What is the oldest civilization?",
        "Why do we have hair?",
        "How do butterflies taste?",
        "What is the magnetic field?",
        "Who was Marie Curie?",
        "What causes drought?",
        "Why do we need oxygen?",
        "How do snakes move?",
        "What is the longest bone?",
        "What is the Ice Age?",
        "How do rain gauges work?",
        "What causes a tornado?",
        "What is the Great Rift Valley?",
        "Why do stars explode?",
        "How fast is a lightning bolt?",
        "How do plants reproduce?",
        "Who was Alexander the Great?",
        "What causes a flood?",
        "Why do we have memories?",
        "What is the polar ice cap?",
        "How do spider webs catch prey?",
        "What is the largest turtle?",
        "Why do we have saliva?",
        "What is the Tropic of Cancer?"
    ]

    list4 = [
        "What if humans could fly?",
        "What if Earth had two moons?",
        "What if dinosaurs survived?",
        "What if gravity stopped?",
        "What if cats could talk?",
        "What if the Sun disappeared?",
        "What if humans lived on Mars?",
        "What if everyone could read minds?",
        "What if time travel existed?",
        "What if oceans were purple?",
        "What if robots had feelings?",
        "What if humans never slept?",
        "What if plants could walk?",
        "What if the Moon had life?",
        "What if Earth stopped spinning?",
        "What if everyone was rich?",
        "What if animals could speak?",
        "What if we had no money?",
        "What if rain fell upward?",
        "What if the sky was green?",
        "What if people had tails?",
        "What if we could breathe underwater?",
        "What if there was no Internet?",
        "What if everyone lived forever?",
        "What if volcanoes froze?",
        "What if gravity doubled?",
        "What if clouds were solid?",
        "What if birds were huge?",
        "What if cars could fly?",
        "What if books read themselves?",
        "What if mirrors showed the future?",
        "What if food grew on trees?",
        "What if everyone had wings?",
        "What if the Earth was flat?",
        "What if winter never ended?",
        "What if sound had color?",
        "What if we could photosynthesize?",
        "What if dogs could drive?",
        "What if all languages vanished?",
        "What if oceans turned fresh?",
        "What if trees could talk?",
        "What if humans had gills?",
        "What if the Moon exploded?",
        "What if stars were close?",
        "What if shadows had secrets?",
        "What if ice never melted?",
        "What if we could teleport?",
        "What if cities floated?",
        "What if every day was Monday?",
        "What if flowers could sing?",
        "What if you woke up tiny?",
        "What if fire was cold?",
        "What if words could heal?",
        "What if we could see sound?",
        "What if the Sun was blue?",
        "What if dinosaurs lived today?",
        "What if gravity turned off at noon?",
        "What if bees were huge?",
        "What if we had no shadows?",
        "What if the Moon was made of cheese?",
        "What if time sped up?",
        "What if the oceans froze?",
        "What if we could fly in space?",
        "What if everyone had super strength?",
        "What if rainbows were solid?",
        "What if the Earth was twice as big?",
        "What if humans hibernated?",
        "What if memories could be downloaded?",
        "What if plants grew instantly?",
        "What if the sky rained candy?",
        "What if the wind stopped?",
        "What if we could talk to ghosts?",
        "What if the Moon followed you?",
        "What if grass was blue?",
        "What if you had a third eye?",
        "What if sleep was optional?",
        "What if stars were tiny?",
        "What if the Sun rose at night?",
        "What if humans could jump high?",
        "What if books were alive?",
        "What if all animals were friendly?",
        "What if the Moon orbited closer?",
        "What if the sky had two suns?",
        "What if we could change color?",
        "What if buildings were alive?",
        "What if water was sticky?",
        "What if we could taste colors?",
        "What if there was no friction?",
        "What if the air was visible?",
        "What if gravity worked sideways?",
        "What if trees walked at night?",
        "What if the sea was warm?",
        "What if humans could glow?",
        "What if the Earth sang?",
        "What if you could pause time?",
        "What if there were aliens next door?",
        "What if the sun rose twice?",
        "What if we could grow wings?",
        "What if music became solid?",
        "What if everyone swapped dreams?",
        "Tell me a funny joke",
        "Give me a riddle",
        "Write a short story",
        "Give me a story idea",
        "Make up a superhero",
        "Give me a random fact",
        "Give me a fun challenge",
        "Write a funny poem",
        "Name my new pet",
        "Give me a brain teaser",
        "Make up a fantasy world",
        "Tell me something weird",
        "Invent a useless invention",
        "Create a funny character",
        "Give me a fun game",
        "Write a love story",
        "Make up a villain",
        "Give me a tongue twister",
        "Write a haiku about rain",
        "Create a secret code",
        "Tell me a funny story",
        "Give me a plot twist",
        "Make up a new holiday",
        "Write a song about pizza",
        "Invent a magic spell",
        "Give me a weird fact",
        "Write a scary story",
        "Create a new word",
        "Make up a planet",
        "Give me a trivia question",
        "Tell me a pun",
        "Write a limerick",
        "Make up a fantasy creature",
        "Give me a writing prompt",
        "Create a funny slogan",
        "Write a short mystery",
        "Invent a new sport",
        "Give me a Would You Rather",
        "Create a comic character",
        "Write a poem about stars",
        "Make up a fictional city",
        "Tell me a funny pick-up line",
        "Give me an animal fact",
        "Write a happy ending",
        "Invent a time machine",
        "Create a new language",
        "Give me a word game",
        "Write a silly song",
        "Make up a dream world",
        "Give me a quirky habit",
        "Create a new animal",
        "Tell me a ghost story",
        "Write a poem about pizza",
        "Give me an idea for a comic",
        "Invent a new color",
        "Make up a secret agent",
        "Give me a math puzzle",
        "Create a funny name",
        "Write a story in 10 words",
        "Give me a mystery plot",
        "Make up a magical object",
        "Tell me a dad joke",
        "Write a funny haiku",
        "Create a new holiday tradition",
        "Invent a gadget",
        "Give me a character name",
        "Write a heroic tale",
        "Make up a new species",
        "Give me a fun survey",
        "Create a nonsense word",
        "Write a mini play",
        "Tell me a riddle for kids",
        "Invent a fantasy map",
        "Give me a random question",
        "Write a poem about the sea",
        "Make up a futuristic city",
        "Give me a drawing idea",
        "Create a silly law",
        "Tell me a funny fact",
        "Write a story starter",
        "Make up a magical pet",
        "Give me a puzzle",
        "Write a song about rain",
        "Create a supervillain name",
        "Tell me something odd",
        "Give me a fun personality quiz",
        "Make up a new dance",
        "Write a horror story",
        "Invent a new instrument",
        "Give me a fun debate topic",
        "Create a fantasy forest",
        "Tell me a knock-knock joke",
        "Write a story about a robot",
        "Make up a board game",
        "Give me a weird idea",
        "Write a poem about summer",
        "Create a time travel plot",
        "Give me a random scenario",
        "Make up a magic school",
        "Write a silly story",
        "Could humans live underwater?",
        "Could a city float?",
        "Can humans live on Mars?",
        "Could dinosaurs return?",
        "Would time travel change history?",
        "Could AI have emotions?",
        "Could we ever teleport?",
        "Could humans breathe underwater?",
        "Could Earth have rings?",
        "Would aliens visit Earth?",
        "Could humans grow wings?",
        "Could the Moon support life?",
        "Could we live on Venus?",
        "Could robots rule the world?",
        "Could humans clone themselves?",
        "Could we travel faster than light?",
        "Could we talk to animals?",
        "Could we live in space?",
        "Could the Sun go out?",
        "Could we stop aging?",
        "Could a robot be funny?",
        "Could we live on the Moon?",
        "Could humans become invisible?",
        "Could we control weather?",
        "Could Earth be a simulation?",
        "Could we live without sleep?",
        "Could we bring back extinct animals?",
        "Could we grow food in space?",
        "Could we live on a comet?",
        "Could we build a space elevator?",
        "Could humans live on Jupiter?",
        "Could we ever time travel?",
        "Could we create a black hole?",
        "Could the Earth stop spinning?",
        "Could we live on a floating island?",
        "Could we colonize Mars?",
        "Could we breathe on Mars?",
        "Could we live underwater cities?",
        "Could we make a real Iron Man?",
        "Could we control dreams?",
        "Could a computer think?",
        "Could we make a lightsaber?",
        "Could we upload our minds?",
        "Could we live on Mercury?",
        "Could we make dragons real?",
        "Could we reverse climate change?",
        "Could we build a Dyson sphere?",
        "Could we make a space colony?",
        "Could we see alien life?",
        "Could we live in a virtual world?",
        "Give me a quick game",
        "Tell me a riddle about time",
        "Write a poem about winter",
        "Create a funny superhero",
        "Give me a weird what-if",
        "Make up a spy story",
        "Write a song about robots",
        "Give me a fun icebreaker",
        "Invent a new card game",
        "Tell me a funny animal",
        "Give me a lateral thinking puzzle",
        "Write a poem about coffee",
        "Create a treasure map",
        "Make up a funny curse",
        "Give me a silly challenge",
        "Write a story about dragons",
        "Create a silly invention",
        "Give me a visual riddle",
        "Tell me a fun history fact",
        "Write a happy poem",
        "Make up a space creature",
        "Give me a two-player game",
        "Write a story about time travel",
        "Create a new mythical beast",
        "Give me a weird conversation starter",
        "Write a poem about the Moon",
        "Invent a crazy sandwich",
        "Tell me a clean joke",
        "Give me a fun trivia question",
        "Create a funny fantasy world",
        "Write a story about a cat",
        "Make up a new language word",
        "Give me a logic puzzle",
        "Tell me something unexpected",
        "Write a poem about rainbows",
        "Create a magical potion",
        "Give me an art prompt",
        "Tell me a silly riddle",
        "Write a story about space",
        "Make up a festival",
        "Give me a fun personality test",
        "Write a poem about snow",
        "Create a weird character",
        "Give me a fun question to ask",
        "Write a short adventure story",
        "Tell me a punny joke",
        "Create a new planet name",
        "Give me a memory puzzle",
        "Write a poem about the ocean",
        "Give me a fantasy writing prompt"
    ]
    return list1,list2,list3,list4

def claude_lists():
    list1 = ["What's Jeff Winger's job before school?", "What's Howard Wolowitz's mom known for?",
             "Who is Ben's father?", "Tell me Creed Bratton's funniest line", "What's Alex Dunphy's biggest fear?",
             "What's The Good Place's best episode?", "What's Penny Hofstadter's last name?",
             'Who does Joey Tribbiani love secretly?', "What's Leonard Hofstadter's catchphrase?",
             "What's Mitchell Pritchett's best trait?", "Tell me Gloria Pritchett's funniest line",
             "What's Chandler Bing's hobby?", "What's Rachel Green's job?", "Who dated Chandler Bing's ex?",
             "What's Jim Halpert's biggest fear?", "What's Dwight Schrute's catchphrase?",
             "What's Ross Geller's worst habit?", 'Who created Parks and Recreation?',
             "What's Lily Aldrin's catchphrase?", "What's Rachel Green's best trait?",
             "What's Mitchell Pritchett's job?", "What's Barney Stinson's job actually?",
             "What's Bernadette's catchphrase?", "What's Leonard's favorite hobby?",
             "Tell me Barney Stinson's famous quote", "What's Lily Aldrin's job?", "What's Rachel Green's hobby?",
             "What's Ross Geller's hobby?", 'What does Sheldon Cooper study?', 'Who is the architect in Good Place?',
             "What's Ross Geller's monkey named?", 'Who created Seinfeld?', "What's Erin Hannon's best trait?",
             "What's Ross Geller's biggest fear?", "What's Chandler Bing's famous line?",
             "What's Monica Geller's best trait?", "What's Alex Dunphy's catchphrase?", "What's Robin's favorite game?",
             "What's Alex Dunphy's job?", "What's Marshall Eriksen's job?", "Who was Joey Tribbiani's roommate?",
             "Tell me Michael Scott's funniest line", "What's Pam Beesly's catchphrase?",
             "Tell me Cameron Tucker's funniest line", "What's Ted Mosby's catchphrase?",
             "What's Erin Hannon's biggest fear?", "Tell me Jay Pritchett's funniest line",
             "What's Barney Stinson's biggest fear?", "What's Creed Bratton's job title?",
             "Who was Ross Geller's first wife?", "Tell me Angela Martin's funniest line",
             'Who is Carlton Banks known for?', "What's Sheldon Cooper's best trait?",
             "What's Amy Farrah Fowler's field?", "What's Ross Geller's famous line?",
             "What's Cameron Tucker's biggest fear?", "Tell me Rachel Green's funniest quote",
             "What's Ross Geller's dinosaur job?", "What's Monica Geller's apartment number?",
             "What's Ted Mosby's biggest fear?", "What's Cameron Tucker's job?",
             "What's Sheldon Cooper's favorite hobby?", "Who is Jim Halpert's wife?",
             "What's Cameron Tucker's catchphrase?", "What's Homer Simpson's job at plant?",
             "What's Phoebe Buffay's worst habit?", "What's Andy Bernard's biggest fear?", 'Who created That 70s Show?',
             "What's Creed Bratton's biggest fear?", "What's Joey Tribbiani's best trait?",
             "What's Kevin Malone's job title?", "What's Amy Farrah Fowler's best trait?", 'Who created The Simpsons?',
             "What's Stanley Hudson's job title?", "What's Andy Bernard's job title?",
             "Who is Sheldon Cooper's best friend?", "What's Gloria Pritchett's best trait?",
             'Who is the mother in HIMYM?', "What's Phoebe Buffay's twin's name?", "What's Ted Mosby's favorite game?",
             "What's Monica Geller's hobby?", "What's Phil Dunphy's real estate motto?",
             "What's Howard Wolowitz's biggest fear?", 'What does Penny Hofstadter study?',
             "What's the slap bet about?", "What's Amy's favorite hobby?", "What's Ross Geller's catchphrase?",
             "What's Manny Delgado's catchphrase?", "What's Leonard Hofstadter's best trait?",
             'Who did Rachel Green leave at altar?', 'Who is the dean in Community?',
             "What's Erin Hannon's catchphrase?", "Tell me Lily Aldrin's famous quote",
             "What's Penny Hofstadter's best trait?", "Tell me Jim Halpert's funniest line",
             "What's Holly Flax's catchphrase?", "What's Captain Holt's personality?",
             "What's Bernadette's best trait?", "Tell me Manny Delgado's funniest line",
             'Who created the Bazinga meme?', "Tell me Pam Beesly's funniest line", "What's Jim Halpert's job title?",
             "What's Sheldon Cooper's knock ritual?", "What's Amy Santiago's binder obsession?",
             "What's Manny Delgado's best trait?", "What's Andy Bernard's best trait?", 'Who created The Good Place?',
             "What's Phoebe Buffay's favorite food?", "What's Raj Koothrappali's best trait?",
             "What's a fun Parks and Recreation fact?", 'What does Amy Farrah Fowler study?',
             "Who is Jake Peralta's partner?", "What's Michael Kelso's catchphrase?", "What's Abed Nadir's obsession?",
             "What's a fun Two and a Half Men fact?", "What's Raj's favorite hobby?",
             "What's Sheldon Cooper's catchphrase?", "Tell me Marshall Eriksen's famous quote",
             "What's Mitchell Pritchett's catchphrase?", "What's Dwight Schrute's job title?",
             "Who is Charles Boyle's best friend?", "What's Raj Koothrappali's catchphrase?",
             "What's Chandler Bing's job in S1?", "What's a fun That 70s Show fact?", "What's a fun The Simpsons fact?",
             "Tell me Howard Wolowitz's funniest line", 'Tell me a Seinfeld catchphrase',
             "What's a fun The Good Place fact?", "What's Ted Mosby's dream job?", 'Who proposed to Monica Geller?',
             "What's a famous The Good Place quote?", "What's Rachel Green's job at end?",
             "What's Phil Dunphy's biggest fear?", "What's Cameron Tucker's best trait?",
             "What's Kevin Malone's chili line?", "What's a famous Community quote?",
             "What's Rachel Green's worst habit?", "What's Sheldon Cooper's roommate deal?",
             'Tell me a The Simpsons catchphrase', "What's Community's best episode?",
             "What's Cameron Tucker's college sport?", "What's Jay Pritchett's job?",
             "What's Barney Stinson's suit rule?", "What's Monica Geller's famous line?", "What's Haley Dunphy's job?",
             "What's Sheldon Cooper's job?", "Tell me Phil Dunphy's funniest line",
             'What does Bernadette Rostenkowski study?', "Tell me Amy's funniest line",
             "What's Manny Delgado's biggest fear?", "What's Leslie Knope's job?",
             "What's Angela Martin's catchphrase?", "What's Bernadette Rostenkowski's job?",
             "What's Robin Scherbatsky's job?", "What's Lily Aldrin's favorite game?", "What's Leonard's biggest fear?",
             'Who is Gunther in love with?', "What's Jay Pritchett's catchphrase?",
             'Tell me a Two and a Half Men catchphrase', "What's Robin Scherbatsky's catchphrase?",
             "Who is Eric Forman's girlfriend?", "What's Joey Tribbiani's famous line?",
             "What's Rachel Green's favorite food?", 'Tell me a Community catchphrase', "What's Howard Wolowitz's job?",
             'Tell me a The Good Place catchphrase', "What's Howard Wolowitz's job title?",
             "What's April Ludgate's personality?", "What's Kevin Malone's best trait?",
             "What's Rachel Green's famous line?", "What's Claire Dunphy's job?",
             "What's Gloria Pritchett's biggest fear?", "What's Michael Scott's boss title?",
             'What does Leonard Hofstadter study?', "What's Chandler Bing's catchphrase?",
             'Who created Two and a Half Men?', "Tell me Penny Hofstadter's funniest line",
             "Tell me Phoebe Buffay's funniest quote", "Tell me Ross Geller's funniest quote",
             "What's Chidi Anagonye's biggest flaw?", "What's Pam Beesly's best trait?",
             "What's Claire Dunphy's best trait?", "What's Barney Stinson's best trait?",
             "What's Moe's Tavern known for?", "Tell me Joey Tribbiani's funniest quote",
             "Tell me Claire Dunphy's funniest line", "Tell me Andy Bernard's funniest line",
             "What's Jim Halpert's catchphrase?", "What's Dwight Schrute's biggest fear?",
             "Tell me Ted Mosby's famous quote", "What's Dwight Schrute's best trait?",
             "What's Amy Farrah Fowler's biggest fear?", "What's Ross Geller's best trait?",
             "What's Jim Halpert's best trait?", 'Who wrote the Playbook?', "Tell me Robin Scherbatsky's famous quote",
             "What's Kevin Malone's biggest fear?", 'Who does Raj Koothrappali struggle with?',
             "What's the blue French horn about?", "What's The Simpsons's best episode?",
             "What's Sheldon Cooper's biggest fear?", "What's Ted Mosby's best trait?",
             "What's Stanley Hudson's best trait?", 'What does Howard Wolowitz study?', 'Who proposed to Bernadette?',
             "What's Penny Hofstadter's job?", 'Who created Fresh Prince of Bel-Air?',
             "What's Rachel Green's catchphrase?", "What's the deal with Unagi?",
             "What's Rachel Green's sister's name?", "Who is Bart Simpson's best friend?",
             "What's Marshall Eriksen's best trait?", 'Who pranks Dwight Schrute the most?',
             "What's Rachel Green's biggest fear?", "What's Luke Dunphy's best trait?",
             "What's Robin Scherbatsky's best trait?", "Tell me Holly Flax's funniest line",
             "What's Haley Dunphy's catchphrase?", "What's Phoebe Buffay's famous line?",
             "What's Joey Tribbiani's biggest fear?", "What's Monica Geller's job?", "Who said 'We were on a break'?",
             "What's Howard Wolowitz's best trait?", "What's Stanley Hudson's biggest fear?",
             "Tell me Leonard's funniest line", "What's Penny Hofstadter's catchphrase?",
             "What's Phil Dunphy's catchphrase?", "What's Angela Martin's best trait?",
             "What's Michael Scott's job title?", "What's Haley Dunphy's best trait?", "What's Penny's favorite hobby?",
             "What's Manny Delgado's job?", "What's Stanley Hudson's catchphrase?", "What's Alex Dunphy's best trait?",
             "What's Central Perk's couch color?", "What's Ted Mosby's job?", "What's Raj Koothrappali's biggest fear?",
             "Who is George Costanza's best friend?", "What's Monica Geller's favorite food?",
             "What's a famous That 70s Show quote?", 'Tell me a Brooklyn Nine-Nine catchphrase',
             "Tell me Haley Dunphy's funniest line", "What's Michael Scott's catchphrase?",
             "What's Raj Koothrappali's job?", 'What does Raj Koothrappali study?', "What's Elaine Benes's dance move?",
             "What's Gloria Pritchett's job?", "What's Angela Martin's job title?", "What's Kramer's entrance style?",
             "What's Jay Pritchett's best trait?", "What's Phoebe Buffay's weirdest song?",
             "What's Ross Geller's favorite food?", "Tell me Bernadette's funniest line",
             "What's Red Forman's famous insult?", "What's Lily Aldrin's best trait?",
             "What's Leonard Hofstadter's job?", "What's Phil Dunphy's best trait?",
             "What's Michael Scott's best trait?", "What's Ross Geller's job?", "Who says 'Legendary' a lot?",
             "What's Jay Pritchett's biggest fear?", "What's Marshall Eriksen's catchphrase?",
             "Tell me Alex Dunphy's funniest line", "What's Barney Stinson's job?", 'Who created Brooklyn Nine-Nine?',
             "What's Chandler Bing's favorite food?", "Tell me Dwight Schrute's funniest line",
             'Who went to space in the show?', "What's Phoebe Buffay's job?", "What's Charlie Harper's job?",
             "What's Manny Delgado's personality like?", "What's a fun Seinfeld fact?", "What's Phil Dunphy's job?",
             "What's Marshall Eriksen's favorite show?", "What's Seinfeld's best episode?",
             "What's Monica Geller's biggest fear?", "What's Joey Tribbiani's job?",
             "What's Luke Dunphy's catchphrase?", "What's Pam Beesly's job title?",
             "What's Gina Linetti's phone obsession?", "What's a famous The Simpsons quote?",
             "Tell me Sheldon Cooper's funniest line", "What's Jerry Seinfeld's job?",
             "Tell me Kevin Malone's funniest line", "What's a fun Community fact?",
             "What's Eleanor Shellstrop's personality?", "What's Marshall Eriksen's biggest fear?",
             "Who is Lily's parent?", "What's Robin Scherbatsky's real name?", "What's Pam Beesly's biggest fear?",
             "What's Angela Martin's biggest fear?", "Who is Angela Martin's cat rival?",
             "What's Monica Geller's worst habit?", "What's Bernadette's favorite hobby?",
             'Who are the main Community characters?', "What's Sheldon Cooper's spot on couch?",
             "What's Lily Aldrin's biggest fear?", "What's Claire Dunphy's catchphrase?",
             "What's Jay Pritchett's old job?", "What's Michael Scott's biggest fear?"]

    list2 = ["What's a good hobby to start?", "What's the best way to reduce stress?",
             "What's the best way to brew coffee?", 'How do I boil an egg?', 'How can I sew a button today?',
             'What should I wear today?', "What's a quick way to relax after work?", 'How do I tidy my kitchen?',
             'How do I avoid back pain?', 'How do I start a budget?', "What's a quick way to reduce stress?",
             'What should I do to find a job?', 'How can I brew coffee today?', 'How do I whiten my teeth?',
             'What should I do to find motivation?', "What's the best way to reduce clutter?",
             "What's a quick way to meal prep?", "What's a quick way to budget monthly?", 'How do I eat healthier?',
             'How can I start running today?', "What's the best way to iron a shirt?", 'How do I whiten teeth?',
             'How can I plan a trip today?', 'How do I remember things better?', "What's a healthy snack?",
             'How do I stay consistent?', 'Any tips to sew a button?', "What's a good desk exercise?",
             'What should I do to whiten teeth?', 'What should I do to study faster?', 'Any tips to wake up early?',
             'Any tips to sleep better?', 'How can I unclog a drain today?', 'How can I whiten teeth today?',
             'How do I organize my closet?', 'How do I plan a road trip?', "What's a quick way to pack light?",
             "What's the best way to remove stains?", 'How do I back up my files?', 'How can I stay focused today?',
             'What should I do to learn a language?', 'What should I do to back up photos?', 'Any tips to save money?',
             'Any tips to read more?', 'Any tips to take notes?', 'How do I stay fit at home?',
             'What book should I read next?', 'How do I save on groceries?', 'How do I invest small amounts?',
             "What's a quick way to save on groceries?", "What's a minimalist packing list?", 'How do I reduce stress?',
             'What should I do to fold laundry?', "What's a quick way to improve posture?",
             'How do I relax after work?', 'How do I save money?', "What's a quick way to eat healthier?",
             'What should I do to fix a leaky faucet?', 'How do I learn a language?', "What's good to watch tonight?",
             'What should I do to sleep better?', "What's the best way to plan a trip?",
             'What should I do to clean my laptop?', 'How do I build a habit?', 'What should I do to plan my day?',
             "What's a quick way to clean windows?", 'How can I meal prep today?', 'How do I plan meals for a week?',
             'How can I read more today?', 'How can I eat healthier today?', "What's a good time management tip?",
             'How do I plan my day?', 'How can I declutter my closet today?', 'How do I clean carpets?',
             'How do I brew coffee?', 'Any tips to remove stains?', "What's a quick way to sew a button?",
             'What should I do to negotiate salary?', 'Any tips to stretch daily?', 'How do I stay productive?',
             'How can I plan my day today?', 'How do I pay off debt?', 'Any tips to stay focused?',
             "What's a quick way to stretch daily?", 'How do I meditate daily?',
             "What's the best way to write a resume?", 'How can I wake up early today?',
             'How can I study faster today?', "What's a good gratitude practice?", 'How do I start journaling?',
             "What's an easy recipe for beginners?", 'What should I do to save for a trip?',
             'What should I do to organize my desk?', "What's a quick way to exercise at home?",
             "What's a quick way to back up photos?", 'Any tips to save on groceries?', 'How can I find a job today?',
             'What should I do to eat healthier?', "What's a quick way to reduce clutter?",
             'How do I build muscle at home?', 'How can I clean my laptop today?', "What's a good ergonomic setup?",
             'What should I do to pay off debt?', 'How can I clean my room today?', 'How can I ace an interview today?',
             "What's the best way to sleep better?", 'How can I clear my inbox today?', 'Any tips to whiten teeth?',
             'What should I do to plan a trip?', 'What should I do to stay hydrated?', 'How do I make coffee at home?',
             "What's a quick way to unclog a drain?", 'How do I pack for a trip?',
             "What's the best way to ace an interview?", 'How do I stay active at work?',
             'How do I set realistic goals?', "What's a quick way to find motivation?", 'How do I clean my laptop?',
             'How can I reduce stress today?', "What's a quick way to find a job?", 'How can I clean windows today?',
             "What's the best way to whiten teeth?", 'How do I clean my room?', 'How do I charge my phone faster?',
             'How do I take a mental break?', "What's a quick way to cook dinner?", 'How can I clean my shoes today?',
             'How can I remove a stain today?', 'Any tips to boost energy?', 'How can I track expenses today?',
             "What's a quick way to start running?", 'How do I clear my inbox?', 'How can I save on groceries today?',
             'How do I track expenses?', 'Any tips to start running?', 'What should I do to stay productive?',
             'Any tips to iron a shirt?', "What's a quick house cleaning tip?",
             "What's a quick way to stay productive?", 'How do I make a to-do list?', "What's an easy one-pan meal?",
             'How can I network better today?', 'How do I stop overthinking?', "What's a budget travel tip?",
             "What's a good stress reliever?", 'What should I do to remove stains?', 'How can I fold laundry today?',
             'Any tips to charge my phone faster?', "What's a good weekly planner app?",
             "What's a quick way to save for a trip?", "What's the best way to manage my time?",
             'What should I do to fall asleep faster?', "What's the best way to start running?",
             "What's a good tea for sleep?", 'Any tips to organize my desk?',
             "What's the best way to learn a language?", "What's a quick way to get organized?",
             "What's the best way to stay motivated?", 'Any tips to declutter my closet?',
             'How can I learn a language today?', 'How can I improve memory today?',
             "What's a quick way to negotiate salary?", 'Any tips to network better?',
             "What's a quick way to boil an egg?", 'Any tips to budget monthly?', 'How can I build a habit today?',
             "What's the best way to clean my shoes?", 'How do I plan a trip?',
             "What's the best way to save for a trip?", 'How do I clean a microwave?', 'How do I ace an interview?',
             'How do I fall asleep faster?', 'How can I budget monthly today?', 'Any tips to tidy my kitchen?',
             "What's a quick way to cut screen time?", 'How do I wake up early?', "What's a good night routine?",
             'What should I do to clean windows?', 'Any tips to remove a stain?',
             "What's the best way to clean windows?", 'What should I do to clean my room?', 'How do I back up photos?',
             "What's a good workout plan?", 'How do I free up phone storage?', "What's a good morning stretch?",
             "What's a good grocery list app?", 'What should I do to reduce stress?',
             "What's a quick way to network better?", "What's the best way to negotiate salary?",
             'What should I do to improve posture?', 'How do I clean windows?', 'Any tips to stop procrastinating?',
             'What should I do to start journaling?', 'How do I sleep better?', 'How can I stop procrastinating today?',
             'Any tips to clean my room?', "What's a quick way to fold laundry?",
             "What's the best way to remove a stain?", 'What should I do to cut screen time?',
             'How can I remove stains today?', 'How can I charge my phone faster today?',
             "What's the best way to stretch daily?", "What's the best way to pay off debt?",
             'How do I reduce screen time?', 'How do I improve posture?', "What's a quick way to pay off debt?",
             "What's the best way to meditate daily?", 'How do I stay accountable?',
             "What's a quick way to manage my time?", 'How do I organize my finances?', 'How can I boost energy today?',
             "What's the best way to clean my room?", 'Any tips to fix a leaky faucet?', 'Any tips to manage my time?',
             'Any tips to clean a microwave?', "What's a quick way to pack for a trip?",
             'What should I do to unclog a drain?', 'How can I stay hydrated today?',
             "What's the best way to cook dinner?", 'How do I start freelancing?', 'Any tips to reduce stress?',
             "What's a productive schedule?", "What's a quick way to sleep better?",
             'What should I do to improve memory?', 'How can I boil an egg today?', 'How do I improve flexibility?',
             'How can I reduce clutter today?', "What's the best way to stay focused?",
             "What's the best way to build a habit?", 'Any tips to study faster?', 'Any tips to save for a trip?',
             "What's a good morning routine?", 'Any tips to fall asleep faster?', 'How do I improve memory?',
             'How can I cook dinner today?', 'How do I get rid of clutter?', 'What should I do to save money?',
             'How can I cut screen time today?', 'How can I pack for a trip today?', 'Any tips to pay off debt?',
             'Any tips to brew coffee?', "What's a quick way to improve memory?",
             "What's the best way to exercise at home?", 'How do I start running?', 'Any tips to unclog a drain?',
             'Any tips to boil an egg?', "What's a quick way to start a budget?",
             "What's the best way to stay productive?", "What's a beginner workout plan?",
             'How do I improve my resume?', "What's the best way to fold laundry?", "What's a good self-care routine?",
             'How do I exercise at home?', 'Any tips to negotiate salary?', 'How can I organize my desk today?',
             'Any tips to pack light?', 'Any tips to exercise at home?', 'How can I get organized today?',
             'How do I organize my desk?', 'How can I start a budget today?', 'How can I stretch daily today?',
             "What's a quick way to stay focused?", 'What can I make with eggs?', 'How do I find motivation?',
             'How do I budget monthly?', 'How can I invest small amounts today?', "What's the best way to take notes?",
             'How do I fix a leaky faucet?', "What's a good skincare routine?", 'How do I iron a shirt?',
             'How do I be more confident?', 'Any tips to clean my laptop?', "What's a good bedtime snack?",
             'How can I stay productive today?', 'What should I do to network better?',
             "What's the best way to cut screen time?", "What's a simple dinner idea?", 'Any tips to relax after work?',
             "What's a quick way to remove stains?", 'Any tips to cook dinner?',
             "What's the best way to find motivation?", 'What should I cook today?', 'How can I sleep better today?',
             'What should I do to stretch daily?', "What's a quick lunch idea?", "What's the best way to read more?",
             "What's a quick way to wake up early?", 'What should I do to clean a microwave?',
             'How can I save for a trip today?', 'How can I cook rice perfectly today?', "What's a cheap dinner idea?",
             "What's the best way to start journaling?", 'What should I do to ace an interview?',
             'What should I do to wake up early?', 'How do I find cheap flights?', 'How do I fold laundry?',
             'How can I write a resume today?', 'How do I manage my time?', "What's the best way to eat healthier?",
             'How can I exercise at home today?']

    list3 = ['Why is the sky blue?', 'How do muscles grow?', 'How does a compass work?',
             "What's the largest continent?", 'How does friction work?', "What's Bluetooth?", 'What causes rainbows?',
             'How do batteries work?', 'How smart are dolphins?', "How hot is the Earth's core?",
             'How does anesthesia numb pain?', 'How does memory work?', "What's momentum?", 'Who discovered gravity?',
             'How was the Moon formed?', 'How do spiders make webs?', "What's climate change?",
             "What's resistance in circuits?", 'How long do redwoods live?', 'How does distillation work?',
             "What's the largest fish?", 'How does exercise help the brain?', 'How was the Grand Canyon formed?',
             "What's the smallest living thing?", 'How does dopamine work?', "What's the largest organ?",
             "What's the largest country?", "What's the hardest natural material?", 'How does hearing work?',
             'How many human races exist?', 'How does metabolism work?', 'Who invented the wheel?',
             'How do airplanes fly?', 'How many oceans are there?', "What's 5G?", 'What causes thunder?',
             'How big is the universe?', "What's the oldest tree on Earth?", 'How is electricity generated?',
             'How does the placebo effect work?', "What's sonar used for?", "What's a solar eclipse?",
             'How does a transformer work?', "What's an acid?", 'Why do cats purr?', 'How were ancient roads built?',
             'How do islands form?', 'How do vaccines work?', "What's the speed of sound?",
             "What's the tallest waterfall?", "What's the oldest language?", 'How long do turtles live?',
             'How do hot air balloons fly?', 'How did farming begin?', "What's a bacteria?",
             'How does stress affect the body?', "What's the most spoken language?", 'How is beer brewed?',
             'Why is the ocean salty?', 'Why do we get goosebumps?', "What's the largest desert?",
             "What's the strongest metal?", 'How do rivers form?', 'How many galaxies exist?',
             "What's the largest bird?", "What's viscosity?", 'How old is the universe?', "What's chlorophyll?",
             "What's serotonin?", "What's the loudest animal?", "What's the rarest language?", 'How old are dinosaurs?',
             "What's a catalyst?", "What's artificial intelligence?", "What's a solstice?",
             'How do fish breathe underwater?', "What's Pangaea?", "What's the speed of light?",
             "What's the origin of money?", "What's the water cycle?", 'How did humans evolve?', 'How old is chess?',
             'Who built the pyramids?', 'How do scientists date fossils?', 'How does a battery store energy?',
             'How is a marathon measured?', "What's the Great Barrier Reef?", "What's the first human species?",
             'How do sharks hunt?', "What's the smallest continent?", 'What causes earthquakes?', 'How do lungs work?',
             'How does vision work?', "What's quantum physics?", 'How does the spine work?', 'How does fog form?',
             "What's the largest ocean?", "What's the coldest place on Earth?", 'How do boats float?',
             'How do penguins survive cold?', "What's the origin of pizza?", "What's the strongest animal?",
             "What's crop rotation?", "What's a black hole?", "What's the driest place on Earth?", "What's a neuron?",
             "What's a leap year?", 'How do continents move?', 'How do seeds grow?', "What's a pacemaker?",
             'How do translators work?', "What's the equator?", 'Why does February have 28 days?',
             "What's carbon dating?", "What's surface tension?", 'Why does it snow?', 'How does photosynthesis work?',
             'How fast does the Earth spin?', "What's cortisol?", 'How does caffeine work?', 'How is tea processed?',
             "What's the origin of agriculture?", 'How were fossils formed?', 'How does GPS work?',
             'How is gold mined?', 'How do submarines work?', "What's the Arctic Circle?", "What's a supernova?",
             "What's a database?", "What's a group of lions called?", "What's the origin of sushi?",
             'How does osmosis work?', "What's Newton's first law?", 'How does the brain store memory?',
             'How do ecosystems work?', 'How is oil formed?', 'How does pH work?', "What's the kidney's function?",
             'How many planets are there?', 'How do nerves send signals?', "What's a semiconductor?",
             'How many days in a year?', "What's the nervous system?", 'How does static electricity work?',
             'How does hypnosis work?', "What's renewable energy?", 'How do magnets work?',
             "What's the human brain made of?", 'How many muscles do humans have?', 'How does the liver work?',
             'How old is the oldest human?', 'How does an X-ray work?', "What's REM sleep?",
             'How does evaporation work?', 'How do plants make food?', "What's the smallest country?",
             "What's protein used for?", "What's an antibiotic?", 'How do bees make honey?',
             "What's the Big Bang theory?", "What's voltage?", 'How was paper invented?',
             'Who was the first astronaut?', "What's condensation?", "What's an IP address?",
             'How does the seasons work?', 'Why do stars shine?', 'How deep is the ocean?',
             'How do polar bears survive?', 'How do clouds form?', 'How many teeth do adults have?', "What's density?",
             'How does the moon affect tides?', 'How many alphabets exist?', "What's the International Space Station?",
             'How does the internet work?', "What's the ozone layer?", "What's fossil fuel?",
             'How does evolution work?', 'How do eclipses happen?', "What's the oldest fossil?",
             'How does acupuncture work?', 'How do earthquakes get measured?', 'How do tsunamis form?',
             "What's the Ring of Fire?", "What's buoyancy?", "What's an MRI scan?", "What's an echo?",
             "What's the pancreas do?", "What's déjà vu?", "What's binary code?", "What's a circuit?",
             "What's a peninsula?", 'How does rust form?', "What's plastic made from?", "What's the tallest animal?",
             "What's the largest animal?", "What's a stethoscope for?", 'How many bones do babies have?',
             'How many countries exist?', "What's the human genome?", "What's genetic engineering?",
             "What's the fastest animal?", 'How do glaciers form?', "What's the origin of vaccines?",
             "What's the Doppler effect?", "What's umami taste?", 'How is steel made?', 'How is cheese made?',
             "What's an insulator?", "What's the largest planet?", 'How do birds migrate?', 'How do cells divide?',
             "What's radioactivity?", "What's the origin of chess?", "What's muscle memory?", "What's oxidation?",
             "What's a lunar eclipse?", 'How do time zones work?', "What's the northern lights?", "What's a comet?",
             'Who painted the Mona Lisa?', 'How is wine made?', 'How does a rainbow form twice?',
             'How does a touchscreen work?', "What's cholesterol?", 'How does a search engine work?',
             "What's the periodic table?", 'How long do elephants live?', 'How does air pressure work?',
             'How does the flu spread?', 'How many bones do humans have?', "What's the driest continent?",
             'How fast can cheetahs run?', "What's the fastest sport?", 'How does yeast infection form?',
             "What's the tallest mountain?", "What's the oldest sport?", 'How much sleep do humans need?',
             "What's the freezing point of water?", 'How does gravity work?', 'How does fermentation work?',
             "What's herd immunity?", 'Why is the sun hot?', "What's the oldest civilization?",
             'How does a virus work?', "What's an algorithm?", "What's the origin of wine?", 'How do ants communicate?',
             "What's diabetes?", 'How is glass made?', 'How do lasers work?', "What's the oldest alphabet?",
             "What's machine learning?", 'How many languages exist?', 'How is rubber made?',
             'How does encryption work?', 'How does ultrasound work?', "What's the fight or flight response?",
             'What causes hurricanes?', 'How was penicillin discovered?', 'How does adrenaline work?',
             'Who invented the printing press?', "What's a stem cell?", "What's the human lifespan average?",
             "What's the largest waterfall?", "What's virtual reality?", 'Who invented the internet?',
             'How did writing begin?', "What's the tallest building?", 'How does the immune system work?',
             'How cold is Antarctica?', 'Who invented the light bulb?', 'How far is the Moon?',
             'How long is a light year?', 'How old is the Earth?', 'How does a VPN work?', "What's the origin of yoga?",
             'How are diamonds formed?', "What's a circadian rhythm?", "What's meditation used for?",
             'How do octopuses camouflage?', 'How is chocolate made?', 'How many elements exist?',
             'How does digestion work?', "What's natural selection?", "What's an equinox?", 'How is bread made?',
             'What is DNA?', "What's the Richter scale?", "What's a meteor shower?", 'How does anesthesia work?',
             "What's the origin of the Olympics?", "What's natural gas?", 'Who wrote Romeo and Juliet?',
             "What's a chemical reaction?", 'How do submarines dive?', 'How do computers work?',
             "What's the jet stream?", "What's the food chain?"]

    list4 = ['Invent a magic school subject', 'What if stars fell to Earth?', 'Give me a short love poem',
             'Could a robot feel pain?', 'What if it rained candy?', 'Name my new pet', 'Give me a time machine rule',
             'Give me an adventure story idea', 'Could we predict earthquakes?', 'Invent a robot personality',
             'Give me a folk tale idea', 'Give me a treasure map idea', 'Invent a new planet',
             'Invent a fictional country', 'What if the ocean was drinkable?', 'Give me a six-word story',
             'Would time travel change history?', 'Invent a futuristic gadget name', 'Write a movie pitch',
             'Give me a weird fact', 'What if the Earth had rings?', 'Write a superhero team name',
             'Invent a new holiday', 'Give me a guessing game', 'Give me a plot for a thriller',
             'Give me a story starter', 'Could humans hibernate?', 'What if school never ended?',
             'Invent a superhero weakness', 'What if dinosaurs survived?', 'Give me a code name for a spy',
             'What if mirrors showed the future?', 'Invent a fictional currency', 'What if animals could vote?',
             'Give me a fun challenge', 'Give me a silly excuse', 'Could a volcano erupt forever?',
             'What if Earth stopped spinning?', 'Give me a spaceship crew name', 'Could a computer become conscious?',
             'Give me a superhero catchphrase', 'What if the sky was green?', 'Could dinosaurs return?',
             'Create a superhero origin', 'What if the Moon had life?', 'Give me a comedy sketch idea',
             'What if robots had feelings?', 'What if the sky had faces?', 'Give me a space station name',
             'What if the internet vanished?', 'Give me a fantasy creature', 'Invent a secret handshake',
             'Give me an interesting fact', 'Invent a new sport', 'Give me a random fact', 'Write a knock-knock joke',
             'Give me a futuristic city idea', 'Give me a word game', 'Give me an April Fools idea',
             'Give me a fantasy kingdom name', 'What if humans never slept?', 'What if the moon exploded?',
             "Write a dragon's backstory", 'Give me a two truths game', 'Test my knowledge',
             'What if everyone had superpowers?', 'Give me a random superpower', 'Could we clone dinosaurs?',
             'Write a limerick', 'Give me a fun fact about animals', 'What if everyone read minds?',
             'What if humans lived on Mars?', 'Give me a logic puzzle', 'Invent a secret language',
             "Could we recycle the ocean's plastic?", 'Give me a song idea', 'Give me a party game idea',
             'Could we build a Dyson sphere?', 'Could a robot become president?', 'Give me a fantasy story idea',
             'Could humans regrow limbs?', 'Give me a name for a potion', 'Write me a haiku',
             'What if humans were tiny?', 'Give me a one-line story', 'Could animals learn human language?',
             "Give me a wizard's spellbook item", 'Invent a new animal', 'Give me a name for a robot',
             'What if Earth had two moons?', 'What if money grew on trees?', 'Give me a drawing prompt',
             'What if you never aged?', 'What if plants could walk?', 'What if oceans were purple?',
             'Give me a superhero name', 'Give me a fun fact about space', 'Tell me a pun', 'Could we terraform Mars?',
             'Give me a superhero sidekick name', 'Give me a band name idea', 'What if fish could talk?',
             'What if humans had tails?', 'What if everyone was invisible?', "Create a time traveler's rule",
             "Write a robot's diary entry", 'What if dogs could drive?', 'What if dragons were real?',
             "Give me a hero's weakness", 'Could humans photosynthesize?', 'Give me a scavenger hunt idea',
             'What if the moon was closer?', 'What if memories could be traded?', 'What if aliens visited Earth?',
             'What if water was purple?', 'Give me a dad joke', 'What if the Moon was a planet?',
             'Could we reverse aging?', 'What if gravity was reversed?', 'Give me a character flaw',
             'What if dreams were shared?', 'What if cars could fly?', 'Give me a name for a wizard',
             'Could humans see in the dark?', 'Could humans survive on the Moon?', 'What if the Earth was flat?',
             'What if wishes came true?', 'Could humans adapt to zero gravity?', 'Could robots replace teachers?',
             'Give me a heist plan idea', 'Give me a joke about cats', 'What if gravity was weaker?',
             'Give me a trivia question', 'Invent a useless invention', 'What if volcanoes stopped erupting?',
             'What if cats could talk?', 'What if cities floated in air?', 'Give me a tongue twister',
             'Give me a villain lair idea', 'Could humans grow gills?', 'Invent a superhero power',
             'Write a pirate story', 'Could AI replace doctors?', 'What if humans had gills?',
             'What if you could read minds?', 'Play twenty questions', 'Give me a personality quiz',
             'Give me a random idea', 'Invent a mythical beast', 'Can humans live on Mars?', 'Give me a made-up word',
             'What if trees could sing?', 'Could we build a moon base?', 'Give me a fantasy map idea',
             'What if colors had sounds?', 'Write a robot love story', 'Give me a creative writing prompt',
             'Give me a fun fact about history', 'Invent an alien language greeting', 'What if the sun turned green?',
             'Invent a dream world rule', 'Could a dragon really fly?', 'What if books wrote themselves?',
             'Give me a fake news headline', 'Give me a random challenge', 'What if music could heal?',
             'Give me a superhero rival', 'Invent a fictional sport rule', 'Make up a superhero',
             'Give me a funny fortune cookie', 'What if gravity stopped?', 'What if the Sun disappeared?',
             'Write a poem about rain', 'Could we upload our minds?', 'Could we talk to whales?',
             'Write a poem about friendship', 'Give me a poem about stars', 'Invent a candy flavor',
             'Give me a 60 second story', 'What if humans lived underground?', 'Write a rap verse',
             'Write a funny limerick', 'Give me a would-you-rather', 'Give me a joke about dogs', 'Invent a slang word',
             'Give me a utopia idea', 'Tell me something weird', "Invent a color that doesn't exist",
             'Give me a spaceship name', 'Give me a spy code name', 'Give me a sci-fi story idea',
             'What if rain fell upward?', 'Invent a magic potion', 'What if humans had echolocation?',
             'Give me a random compliment', 'What if time travel existed?', 'Could time loops exist?',
             'What if shadows had minds?', 'Could plants feel pain?', 'Give me a plot twist idea',
             'Give me a mystery plot', 'Give me a math riddle', 'Create a funny character',
             'Give me a fairy tale twist', 'Could animals build cities?', 'Give me a creative challenge',
             'What if numbers had colors?', 'Could a computer dream?', 'Invent a mythical land',
             'Give me a poem about the sea', 'What if the sun was blue?', 'Could aliens be among us?',
             'Give me a dystopia idea', 'What if humans breathed water?', 'What if the ocean vanished?',
             'Invent a gadget', 'Invent a secret society', "Give me a robot's first words", 'Give me a villain name',
             'What if animals wrote books?', 'Could humans live without oxygen?', 'Give me a doodle idea',
             'Could a robot dream?', 'Could the moon crash into Earth?', 'Give me an alien greeting',
             'Could humans breathe on Mars?', 'What if the internet never existed?', 'Could a black hole be tamed?',
             'Give me a new emoji idea', 'Write a short story', 'Give me a myth idea', 'Invent a board game',
             'Give me a treasure hunt clue', 'Could a black hole eat Earth?', 'Give me an icebreaker question',
             'What if snow was warm?', 'Invent a fantasy weapon', 'Tell me a plot twist', 'Give me a riddle about time',
             'Could we live inside a computer?', 'What if winter never ended?', 'Give me a scary story idea',
             'What if humans could fly?', 'Could ghosts be real?', 'Could AI have emotions?',
             'Give me a space adventure', 'Give me a mystery story idea', 'Could we live without sleep?',
             'What if the past could be changed?', 'What if the Earth was cube shaped?',
             'Could humans live underwater?', 'Give me a plot for a comedy', 'Invent a magical object',
             'What if robots ruled the world?', 'What if clouds were solid?', "Give me a detective's catchphrase",
             'Give me a pirate ship name', 'Tell me a funny joke', 'Give me a alien species idea',
             'Invent a superhero costume', 'Could we build a space elevator?', 'What if dreams became real?',
             'Give me a nickname idea', 'What if you could pause time?', 'What if animals ruled Earth?',
             'Give me a brain teaser', 'Give me a campfire story', 'What if you could talk to plants?',
             'Write a bedtime story', 'What if humans glowed in dark?', 'Create a talking animal',
             'What if fire was cold?', "Give me a villain's plan", 'What if humans had wings?',
             'Give me a fantasy quest idea', 'Could AI write a novel?', 'Could humans teleport someday?',
             'Give me a ghost story', 'What if books could talk?', 'Write a haunted house story',
             'Give me a motivational quote', 'What if time moved backward?', 'Give me a fun fact about food',
             'What if humans lived forever?', 'Give me a story idea', 'Could robots fall in love?',
             'Name a fictional planet', 'Could a city exist underwater?', 'Give me a name for a dragon',
             'Could we control weather?', 'Make up a fantasy world', 'Give me a riddle', 'Give me a fun game',
             'Could a city float?', "Write a villain's monologue", 'Create a magic spell', 'Write a funny poem',
             'What if you could shrink yourself?', 'Give me a legend idea', 'Surprise me with something fun']
    return list1,list2,list3,list4